name: Deploy Storybook

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - deploy-storybook-gh-action

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  deploy-storybook:
    # Name the Job
    name: Deploy Storybook to GitHub pages
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run build:storybook

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@3.7.1
        run: |
          git config --global user.name "simorgh-bbc"
          git config --global user.email "DENewsSimorghDev@bbc.co.uk"
        with:
          GIT_CONFIG_NAME: simorgh-bbc
          GIT_CONFIG_EMAIL: DENewsSimorghDev@bbc.co.uk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: storybook_dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
