name: Simorgh CI - Unit Tests
on:
  push:
    branches:
      - '**'
      - '!latest'
  pull_request:
    branches:
      - '**'
      - '!latest'
jobs:
  env:
    CI: true
    LOG_LEVEL: 'error'

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules
        run: npm ci

      - name: Apache License Checker
        run: npx apache2-license-checker

      - name: Duplicate Dependency Checker
        run: npm run test:dependencies

      - name: Linting
        run: npm run test:lint

      - name: Chromatic UI Tests # we should only run these one, they currently run on codebuild
        run: # npx chromatic test run --build-script-name build:storybook --exit-once-uploaded --no-interactive
