name: Simorgh CI - Cypress E2E Tests
on:
  create:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - latest
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.14.1-chrome83-ff77
      options: --user 1001 --shm-size=2g
    env:
      CI: true
      LOG_LEVEL: 'error'
      CYPRESS_SKIP_EU: true
      CYPRESS_SMOKE: true
      CYPRESS_APP_ENV: 'local'
      DEBUG: 'cypress:*'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Simorgh E2Es
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start
          
